### ISSUE TITLE
Add option to remove or customize "copy to clipboard" button in `ui_combo_12`

### ISSUE THREAD

**Issue by juh9870** [frankvgompel/egui_colors#11]
"copy to clipboard" button can be pretty out of place, especially once #10 is merged, and applications might want to use serde for serializing and sharing theme data.

In its current state, the "copy to clipboard" button copies theme in the Debug format, which is almost useless besides visually showing other people in plain text, since you would need to write some custom parser to parse it back into machine-readable theme

**Comment by frankvgompel** [comment]
I will give this some thought although I have had some use for it myself.

**Comment by juh9870** [comment]
It can be kept as an optional feature (tho it's pretty trivial to write those 3 lines of code in downstream apps that actually do need it)

**Comment by frankvgompel** [comment]
1367ed3e741773b21d26e946942e70aeb442e5a0
Hope this suffices.
