### ISSUE TITLE
Add methods for toggling dark mode

### ISSUE THREAD

**Issue by juh9870** [frankvgompel/egui_colors#12]
`light_dark_toggle_button` has a fixed size that poorly fits into the menubar, so it would be nice to have an option to use a custom widget for light/dark mode, and just call a method on colorix to set light/dark mode.

Making a custom widget is impossible right now due to colorix holding all color management pretty tightly inside itself, and not exposing any API to deal with it.

![image](https://github.com/user-attachments/assets/29a5f068-b464-4877-b84c-ff6824072c1a)

**Comment by frankvgompel** [comment]
That is a good idea. Will look into it.

**Comment by frankvgompel** [comment]
Added `set_dark` and `set_light` methods.
